<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Macro del cassone trainato -->
  <!-- param:
       parent_link : link del robot a cui agganciare il cassone (es. base_link)
  -->
  <xacro:macro name="fra2mo_trailer" params="parent_link">

    <!-- Proprietà base del cassone -->
    <xacro:property name="trailer_length" value="0.4"/>  <!-- X -->
    <xacro:property name="trailer_width"  value="0.4"/>  <!-- Y -->
    <xacro:property name="trailer_height" value="0.1"/>  <!-- Z: DIMEZZATO (0.2 -> 0.1) -->
    <xacro:property name="trailer_mass"   value="0.05"/>

    <!-- Proprietà ruote -->
    <xacro:property name="wheel_radius" value="0.12"/>
    <xacro:property name="wheel_width"  value="0.04"/>



    <!-- Link del cassone -->
    <link name="trailer_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${trailer_mass}" />
        <inertia ixx="0.02" ixy="0.0" ixz="0.0"
                 iyy="0.02" iyz="0.0" izz="0.02" />
      </inertial>

      <!-- Cassone: box -->
      <xacro:property name="wall_thickness" value="0.02"/>

      <visual>
         <origin xyz="0 0 -0.2" rpy="0 0 0" />
        <geometry>
          <box size="${trailer_length} ${trailer_width} ${wall_thickness}"/>
        </geometry>
        <material name="TrailerGrey">
          <color rgba="0.6 0.6 0.6 1"/>
        </material>
      </visual>

      <visual>
        <origin xyz="${-trailer_length/2.0 + wall_thickness/2.0} 0 -0.14"/>
        <geometry>
          <box size="${wall_thickness} ${trailer_width} ${trailer_height}"/>
        </geometry>
        <material name="TrailerGrey"/>
      </visual>

      <visual>
        <origin xyz="${trailer_length/2.0 - wall_thickness/2.0} 0 -0.14"/>
        <geometry>
          <box size="${wall_thickness} ${trailer_width} ${trailer_height}"/>
        </geometry>
        <material name="TrailerGrey"/>
      </visual>

      <visual>
        <origin xyz="0 ${-trailer_width/2.0 + wall_thickness/2.0} -0.14"/>
        <geometry>
          <box size="${trailer_length} ${wall_thickness} ${trailer_height}"/>
        </geometry>
        <material name="TrailerGrey"/>
      </visual>

      <visual>
        <origin xyz="0 ${trailer_width/2.0 - wall_thickness/2.0} -0.14"/>
        <geometry>
          <box size="${trailer_length} ${wall_thickness} ${trailer_height}"/>
        </geometry>
        <material name="TrailerGrey"/>
      </visual>


      <!-- Collision-->
      <!-- collision pavimento cassone-->
      <collision>
          <origin xyz="0 0 -0.2" rpy="0 0 0" />
        <geometry>
          <box size="${trailer_length} ${trailer_width} ${wall_thickness}"/>
        </geometry>
      </collision>
      <!-- collision pareti cassone-->
      <collision>
        <origin xyz="${-trailer_length/2.0 + wall_thickness/2.0} 0 -0.14"/>
        <geometry>
          <box size="${wall_thickness} ${trailer_width} ${trailer_height}"/>
        </geometry>
      </collision>

      <collision>
        <origin xyz="${trailer_length/2.0 - wall_thickness/2.0} 0 -0.14"/>
        <geometry>
          <box size="${wall_thickness} ${trailer_width} ${trailer_height}"/>
        </geometry>
      </collision>

      <collision>
        <origin xyz="0 ${-trailer_width/2.0 + wall_thickness/2.0} -0.14"/>
        <geometry>
          <box size="${trailer_length} ${wall_thickness} ${trailer_height}"/>
        </geometry>
      </collision>

      <collision>
        <origin xyz="0 ${trailer_width/2.0 - wall_thickness/2.0} -0.14"/>
        <geometry>
          <box size="${trailer_length} ${wall_thickness} ${trailer_height}"/>
        </geometry>
      </collision>
    </link>

    <!-- Giunto tra robot e cassone -->
    <!-- Posizionato SOPRA AL FRA2MO come una torre (z=0.40 per stare ben in alto) -->
    <joint name="fra2mo_trailer_joint" type="fixed">
      <parent link="base_link"/>
      <child  link="trailer_link"/>
      <origin xyz="0 0 0.37" rpy="0 0 0"/>
      <!-- snodo in yaw -->
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="20" velocity="1.0"/>
      <dynamics damping="10.0" friction="2.0"/>
    </joint>

  

    <!-- ===================== -->
    <!-- Ruote del cassone - DISABILITATE (no ruote) -->
    <!-- ===================== -->

    <!-- COMMENTATO: Ruota sinistra 
    <link name="trailer_wheel_left_link">
      <inertial>
        <origin xyz="0 0 -0.3"/>
        <mass value="0.05"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
      <visual>
        <origin xyz="0 0 -0.3" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="WheelBlack">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 -0.3" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="trailer_wheel_left_joint" type="continuous">
      <parent link="trailer_link"/>
      <child  link="trailer_wheel_left_link"/>
      <origin xyz="0 ${-trailer_width/2.0} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.2"/>
    </joint>

    COMMENTATO: Ruota destra
    <link name="trailer_wheel_right_link">
      <inertial>
        <origin xyz="0 0 -0.3"/>
        <mass value="0.05"/>
        <inertia ixx="0.001" ixy="0.0" ixz="0.0"
                 iyy="0.001" iyz="0.0" izz="0.001"/>
      </inertial>
      <visual>
        <origin xyz="0 0 -0.3" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="WheelBlack">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 -0.3" rpy="${pi/2} 0 0"/>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="trailer_wheel_right_joint" type="continuous">
      <parent link="trailer_link"/>
      <child  link="trailer_wheel_right_link"/>
      <origin xyz="0 ${trailer_width/2.0} ${wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <dynamics damping="0.1" friction="0.2"/>
    </joint>
    -->


    

  </xacro:macro>

</robot>
